import "./globals.scss";
import Providers from "./queryProvider";

export const metadata = {
    title: "What2Watch",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
